[package]
name = "rastman"
version = "0.1.0"
authors = ["Vitalii A. Petrenko <v.petrenko@space-flow.dev>"]
edition = "2021"

[dependencies]
iced = "0.14.0"
iced_test = "0.14.0"
serde_json = "1.0.145"
reqwest = "0.12.24"
rayon = "1.11.0"
